name: CI - Sanity Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python dependencies
        run: uv sync --python ${{ matrix.version }}

      - name: Check code style pre-commit hooks
        uses: pre-commit/action@v3.0.1

      - name: Run lit tests
        run: uv run --python ${{ matrix.version }} lit -v tests
